# -*- coding: utf-8 -*-
#
# OPEA Project documentation build configuration file
#
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath('.'))

# Get OPEA version from GenAIComps/comps/version.py
sys.path.insert(0, os.path.abspath("../../../GenAIComps/comps"))
from version import __version__

RELEASE = ""
if "RELEASE" in os.environ:
   RELEASE = os.environ["RELEASE"]

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

sys.path.insert(0, os.path.join(os.path.abspath('.'), 'sphinx/extensions'))
extensions = [
   'sphinx.ext.graphviz',
   'sphinxcontrib.jquery',
   'sphinx_tabs.tabs',
   # 'last_updated',
   'myst_parser',
   'sphinxcontrib.mermaid',
   'link_roles',
   #'sphinx_md',
]

# myst settings
myst_heading_anchors = 1

# sphinx_md config
sphinx_md_useGitHubURL = True

graphviz_output_format='png'
graphviz_dot_args=[
   '-Nfontname="verdana"',
   '-Gfontname="verdana"',
   '-Efontname="verdana"']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['sphinx/_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md',
                 ]

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'OPEA™'
this_year=str(datetime.now().year);
copyright = u'2024' + ('' if this_year == '2024' else ('-' + this_year)) + ' ' + project + ', a Series of LF Projects, LLC'
author = u'OPEA Project developers'

version = release = __version__
if not version:
  sys.stderr.write('Warning: Could not extract OPEA version from version.py\n')
  version = release = "unknown"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
        'scripts/*',
        ]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
try:
    import sphinx_rtd_theme
except ImportError:
    html_theme = 'alabaster'
    # This is required for the alabaster theme
    # refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
    html_sidebars = {
        '**': [
            'relations.html',  # needs 'show_related': True theme option to display
            'searchbox.html',
            ]
        }
    sys.stderr.write('Warning: sphinx_rtd_theme missing. Use pip to install it.\n')
else:
    html_theme = "sphinx_rtd_theme"
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
    html_theme_options = {
        'canonical_url': '',
        'analytics_id': 'G-3QH5804YP8',
        'logo_only': False,
        'display_version': True,
        #'prev_next_buttons_location': 'None',
        # Toc options
        'collapse_navigation': False,
        'sticky_navigation': True,
        'navigation_depth': 4,
    }


# Here's where we (manually) list the document versions maintained on
# the published doc website.  On a daily basis we publish to the
# /latest folder but when releases are made, we publish to a /<relnum>
# folder (specified via the VERSION file as processed earlier or
# overridden on the make command line with RELEASE=name.

if tags.has('release'):
   is_release = True
   docs_title = '%s' %(version)
   current_version = version
   if RELEASE:
      version = release = current_version = RELEASE
      docs_title = '%s' %(version)
else:
   version = current_version = "latest"
   is_release = False
   docs_title = 'Latest'

html_context = {
   'current_version': current_version,
   'docs_title': docs_title,
   'is_release': is_release,
   'versions': ( ("latest", "/latest/"),
                 # ("1.0", "/1.0/"),   # just to check that version picker works
               )
    }


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

html_logo = 'images/opea-horizontal-white-w200.png'
html_favicon = 'images/OPEA-favicon-32x32.png'

numfig = True
#numfig_secnum_depth = (2)
numfig_format = {'figure': 'Figure %s', 'table': 'Table %s', 'code-block': 'Code Block %s'}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['sphinx/_static']

def setup(app):
   import sphinx

   if float(sphinx.__version__[0:3]) < 3.0:
      app.add_stylesheet("opea-custom.css")
      # app.add_javascript("https://www.googletagmanager.com/gtag/js?id=UA-831873-64")
      # note more GA tag manager calls are in acrn-custom.js
      app.add_javascript("opea-custom.js")
   else:
      app.add_css_file("opea-custom.css")
      # we removed the old google analytics codes in favor or enabling analytics
      # via the "analytics_id" provided by sphinx_RTD_theme
      # app.add_js_file("https://www.googletagmanager.com/gtag/js?id=UA-831873-64")
      app.add_js_file("opea-custom.js")

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If not '', a 'Last updated on:' timestamp is inserted at every page
# bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'



rst_epilog = """
.. include:: /sphinx/substitutions.txt
"""

# Custom last_updated extension for updating last updated date based on git information
# needs to know the folders where the cloned files can be found, relative to
# where the Sphinx .rst build folder

# last_updated_git_path = ['../..', '../../..', '../../../doc/']
